import type { PropertyListing } from '@/types/property/property.types';

export const MOCK_PROPERTY_LISTINGS: PropertyListing[] = [
  {
    id: '1',
    title: 'Cho thuê BT Vườn Đào 55 triệu, 165m2, 6PN 4WC view đẹp tại Tây Hồ',
    type: 'Nhà biệt thự',
    bedrooms: 6,
    bathrooms: 4,
    project: 'Vườn Đào',
    priceDisplay: '55 triệu/tháng',
    priceValue: 55,
    area: '165 m²',
    areaValue: 165,
    location: 'Phường Phú Thượng (P. Phú Thượng mới)',
    timePosted: '16 phút trước',
    timestamp: new Date(Date.now() - 16 * 60000).getTime(),
    imageCount: 10,
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDRc7jN5ynih8q5YPoualBZeNcWP1rFPJDIAOMz8i3ejq0qIcTSu77Je8t-OYEnN5to5EQ5WhLMrZH8-yvmRJAbpvO1_skMB0p48ueP0uXInqIfJ4ISyases5sVmfb6h7xTenH0oXxUG6QJWX0VvgePN5ZrPvs1sxXROdw5JGytp6TH_zDBwc3XAGhf9Xt3_YKQL5IxdsIuNYBU42so0rIzHSUP2uJj6p4os3mva-lCtNOVjf4H2JsdlZaZJ7QykvytauUV6KfW1e8q',
    author: { name: 'Dương Quang', initial: 'D', posts: 1 },
  },
  {
    id: '2',
    title: 'Cho thuê căn hộ cao cấp Vinhomes Central Park, 2PN 2WC full nội thất',
    type: 'Căn hộ chung cư',
    bedrooms: 2,
    bathrooms: 2,
    project: 'Vinhomes Central Park',
    priceDisplay: '25 triệu/tháng',
    priceValue: 25,
    area: '80 m²',
    areaValue: 80,
    location: 'Phường 22, Quận Bình Thạnh',
    timePosted: '1 giờ trước',
    timestamp: new Date(Date.now() - 60 * 60000).getTime(),
    imageCount: 8,
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCIppfThWyPwMftRP9EaywHa4O38BeW6Bi5l_gyBP1A8GpDOJ6bsHpS2G0VnTpJnT9V3lHvDjRaeir46CatUhF3Xjt01op1m631oXBedCNgq_Xxj_nD7Fb-dwmR1ol25I8VpN-pJWdTsyY5p_PUAI7PbGs2tJssCzeRRo4x8uVAcQSjfqZUh4-wo73Cg0uan2CiB5yH2Mr-Ip3T5QOUrwUfvSicjO8zkMBgHGJXc6ahTgLFv99-uSAvbNEHSNVixwzMxNtgWQRIb37m',
    author: { name: 'Minh Tuấn', initial: 'M', posts: 5 },
  },
  {
    id: '3',
    title: 'Cho thuê nhà nguyên căn mặt tiền đường Nguyễn Đình Chiểu, Quận 3',
    type: 'Nhà mặt phố',
    bedrooms: 4,
    bathrooms: 4,
    project: null,
    priceDisplay: '40 triệu/tháng',
    priceValue: 40,
    area: '120 m²',
    areaValue: 120,
    location: 'Phường 6, Quận 3',
    timePosted: '3 giờ trước',
    timestamp: new Date(Date.now() - 180 * 60000).getTime(),
    imageCount: 12,
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBnNOrg5V-TJXOnprDulFf6cxnqTUhZ6-AOPRVh6jDp1bPH_hZ8uSbYqnEfkjP7K9xgjj6qNZPlvrVQvMQ-pAG_bqAAr1pb3IjX7Mo0PFgG1G-9QaBBWc8v5bnKMk4ZA1GUAkvDwe6CLoDzM5GRWdTaYHYyT_QdA1E1g2Y_o2EB36OFch4o5icUWgRBpEWitt2e5-g25PUJAA9hk1g31uTMaolncQl-tkXxJ4kI2Vkx7fENhR9wGPO0C3fshuQQJ20qRjc1sFCCFDuP',
    author: { name: 'Lan Anh', initial: 'L', posts: 2 },
  },
  {
    id: '4',
    title: 'Phòng trọ khép kín, an ninh tốt gần Đại học Quốc Gia',
    type: 'Phòng trọ',
    bedrooms: 1,
    bathrooms: 1,
    project: null,
    priceDisplay: '3.5 triệu/tháng',
    priceValue: 3.5,
    area: '25 m²',
    areaValue: 25,
    location: 'Phường Dịch Vọng Hậu, Cầu Giấy',
    timePosted: '5 giờ trước',
    timestamp: new Date(Date.now() - 300 * 60000).getTime(),
    imageCount: 4,
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800',
    author: { name: 'Cô Hoa', initial: 'H', posts: 12 },
  },
  {
    id: '5',
    title: 'Biệt thự mini siêu đẹp khu đô thị Sala, đầy đủ tiện nghi',
    type: 'Nhà biệt thự',
    bedrooms: 4,
    bathrooms: 5,
    project: 'KĐT Sala',
    priceDisplay: '80 triệu/tháng',
    priceValue: 80,
    area: '200 m²',
    areaValue: 200,
    location: 'KĐT Sala, Quận 2',
    timePosted: '1 ngày trước',
    timestamp: new Date(Date.now() - 1440 * 60000).getTime(),
    imageCount: 15,
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=800',
    author: { name: 'Trần Phong', initial: 'P', posts: 8 },
  },
  {
    id: '6',
    title: 'Căn hộ mini giá rẻ cho sinh viên, người đi làm',
    type: 'Căn hộ mini',
    bedrooms: 1,
    bathrooms: 1,
    project: null,
    priceDisplay: '6 triệu/tháng',
    priceValue: 6,
    area: '35 m²',
    areaValue: 35,
    location: 'Quận Đống Đa, Hà Nội',
    timePosted: '2 ngày trước',
    timestamp: new Date(Date.now() - 2880 * 60000).getTime(),
    imageCount: 5,
    image: 'https://images.unsplash.com/photo-1502672260266-1c1e525044c7?auto=format&fit=crop&q=80&w=800',
    author: { name: 'Lê Nam', initial: 'N', posts: 3 },
  },
];
