export const ROUTES = {
  home: '/',
  search: '/search',
  guide: '/guide',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  verifyEmail: '/verify-email',
  contact: '/contact',
  about: '/about',
  privacy: '/privacy',
  profile: '/profile',
  manageRentals: '/manage-rentals',
  adminPostProperty: '/admin/post-property',
  adminBlog: '/admin/blog',
  adminBlogNew: '/admin/blog/new',
  adminBlogEdit: (id: string | number) => `/admin/blog/${id}/edit`,
  adminContact: '/admin/contact',
  adminContactMessages: '/admin/contact/messages',
  saved: '/saved',
  notifications: '/notifications',
  settings: '/settings',
  blog: '/blog',
  blogDetail: (id: string | number) => `/blog/${id}`,
  propertyDetail: (id: string | number) => `/property/${id}`,
} as const;
